In [1]:
import pandas as pd
import os

In [2]:
data_dir = '../data/csv/original/second/'
data_list = os.listdir(data_dir)
data_list

['By Sectors-By Sectors (World Bank definition) (Nominal Bil. IDR).csv',
 'By Economic classification-By Economic classification (Nominal Bil. IDR).csv',
 'By Functions-By Functions (Government of Indonesia  on the effort to be accordance with COFOG definition) (Nominal Bil. IDR).csv']

In [3]:
class_df = pd.read_csv(data_dir + data_list[1], header=1, skipinitialspace=True)

In [4]:
class_df

,"Central (excl. transfers, subsidy and interest payment)+provinces+districts",2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1_Personnel,"85,104","86,154","109,702","126,677","132,353","167,556","211,616","261,345","295,891",...,"458,807","514,048","556,475","610,335","656,987","669,442","714,751","761,043","753,832","763,785"
1,2_Goods and services,"30,227","40,389","47,805","49,593","68,854","105,155","110,363","122,548","155,791",...,"261,398","315,330","342,018","426,136","470,937","539,377","615,647","639,205","697,304","845,871"
2,3_Capital,"58,398","61,604","102,772","92,241","69,931","119,802","152,854","170,638","178,323",...,"275,147","368,450","328,340","424,088","392,230","420,309","387,364","396,755","348,492","406,986"
3,4_Grants,-,-,-,-,-,-,"3,916","11,352","11,782",...,"46,513","53,144","54,439","69,188","79,484","73,188","80,351","80,629","94,965","84,008"
4,5_Others (include financial/social assistance ...,"14,221","20,299","28,442","25,967","46,276","54,328","37,043","57,070","65,349",...,"24,993","31,831","40,502","67,751","96,209","121,760","131,549","143,709","285,223","215,415"
5,6_Social Assistance (only at central level),NaN,NaN,NaN,NaN,"24,904","40,709","49,756","57,741","73,814",...,"75,621","92,136","97,925","97,151","49,614","55,297","84,318","112,480","202,530","173,654"
6,Total (excl. subsidy and interest payment),"187,950","208,446","288,720","294,478","342,318","487,550","565,549","680,694","780,950",...,"1,142,480","1,374,940","1,419,698","1,694,649","1,745,460","1,879,373","2,013,980","2,133,822","2,382,345","2,489,720"
7,Subsidies,"77,443","40,006","43,899","91,529","120,765","107,432","150,214","275,291","138,082",...,"346,420","355,045","391,963","185,971","174,227","166,401","216,883","201,803","196,231","242,087"
8,Interest payments,"87,142","87,667","65,351","62,485","65,200","79,083","79,806","88,430","93,782",...,"100,516","113,035","133,441","156,010","182,761","216,568","257,952","275,521","314,088","343,495"
9,Total (incl. subsidy and interest payment),"352,536","336,119","397,969","448,492","528,283","674,065","795,570","1,044,415","1,012,814",...,"1,589,416","1,843,021","1,945,101","2,036,629","2,102,448","2,262,342","2,488,815","2,611,145","2,892,665","3,075,302"
10,For information:,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,Transfers (from Central to sub-national levels),"81,054","94,657","120,314","129,723","150,464","226,180","253,263","292,434","308,585",...,"480,645","513,260","573,703","623,140","710,257","741,992","757,793","812,973","762,530","785,708"

In [6]:
class_df = class_df.drop(10, axis=0)

In [7]:
class_df

,"Central (excl. transfers, subsidy and interest payment)+provinces+districts",2001,2002,2003,2004,2005,2006,2007,2008,2009,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
0,1_Personnel,"85,104","86,154","109,702","126,677","132,353","167,556","211,616","261,345","295,891",...,"458,807","514,048","556,475","610,335","656,987","669,442","714,751","761,043","753,832","763,785"
1,2_Goods and services,"30,227","40,389","47,805","49,593","68,854","105,155","110,363","122,548","155,791",...,"261,398","315,330","342,018","426,136","470,937","539,377","615,647","639,205","697,304","845,871"
2,3_Capital,"58,398","61,604","102,772","92,241","69,931","119,802","152,854","170,638","178,323",...,"275,147","368,450","328,340","424,088","392,230","420,309","387,364","396,755","348,492","406,986"
3,4_Grants,-,-,-,-,-,-,"3,916","11,352","11,782",...,"46,513","53,144","54,439","69,188","79,484","73,188","80,351","80,629","94,965","84,008"
4,5_Others (include financial/social assistance ...,"14,221","20,299","28,442","25,967","46,276","54,328","37,043","57,070","65,349",...,"24,993","31,831","40,502","67,751","96,209","121,760","131,549","143,709","285,223","215,415"
5,6_Social Assistance (only at central level),NaN,NaN,NaN,NaN,"24,904","40,709","49,756","57,741","73,814",...,"75,621","92,136","97,925","97,151","49,614","55,297","84,318","112,480","202,530","173,654"
6,Total (excl. subsidy and interest payment),"187,950","208,446","288,720","294,478","342,318","487,550","565,549","680,694","780,950",...,"1,142,480","1,374,940","1,419,698","1,694,649","1,745,460","1,879,373","2,013,980","2,133,822","2,382,345","2,489,720"
7,Subsidies,"77,443","40,006","43,899","91,529","120,765","107,432","150,214","275,291","138,082",...,"346,420","355,045","391,963","185,971","174,227","166,401","216,883","201,803","196,231","242,087"
8,Interest payments,"87,142","87,667","65,351","62,485","65,200","79,083","79,806","88,430","93,782",...,"100,516","113,035","133,441","156,010","182,761","216,568","257,952","275,521","314,088","343,495"
9,Total (incl. subsidy and interest payment),"352,536","336,119","397,969","448,492","528,283","674,065","795,570","1,044,415","1,012,814",...,"1,589,416","1,843,021","1,945,101","2,036,629","2,102,448","2,262,342","2,488,815","2,611,145","2,892,665","3,075,302"
11,Transfers (from Central to sub-national levels),"81,054","94,657","120,314","129,723","150,464","226,180","253,263","292,434","308,585",...,"480,645","513,260","573,703","623,140","710,257","741,992","757,793","812,973","762,530","785,708"

In [8]:
class_df.rename(columns={class_df.columns[0]: 'Year'}, inplace=True)
class_df = class_df.set_index('Year')

In [9]:
class_df

,2001,2002,2003,2004,2005,2006,2007,2008,2009,2010,...,2012,2013,2014,2015,2016,2017,2018,2019,2020,2021
Year,,,,,,,,,,,,,,,,,,,,,
1_Personnel,"85,104","86,154","109,702","126,677","132,353","167,556","211,616","261,345","295,891","348,955",...,"458,807","514,048","556,475","610,335","656,987","669,442","714,751","761,043","753,832","763,785"
2_Goods and services,"30,227","40,389","47,805","49,593","68,854","105,155","110,363","122,548","155,791","178,306",...,"261,398","315,330","342,018","426,136","470,937","539,377","615,647","639,205","697,304","845,871"
3_Capital,"58,398","61,604","102,772","92,241","69,931","119,802","152,854","170,638","178,323","174,451",...,"275,147","368,450","328,340","424,088","392,230","420,309","387,364","396,755","348,492","406,986"
4_Grants,-,-,-,-,-,-,"3,916","11,352","11,782","15,231",...,"46,513","53,144","54,439","69,188","79,484","73,188","80,351","80,629","94,965","84,008"
5_Others (include financial/social assistance in district level),"14,221","20,299","28,442","25,967","46,276","54,328","37,043","57,070","65,349","46,434",...,"24,993","31,831","40,502","67,751","96,209","121,760","131,549","143,709","285,223","215,415"
6_Social Assistance (only at central level),NaN,NaN,NaN,NaN,"24,904","40,709","49,756","57,741","73,814","68,611",...,"75,621","92,136","97,925","97,151","49,614","55,297","84,318","112,480","202,530","173,654"
Total (excl. subsidy and interest payment),"187,950","208,446","288,720","294,478","342,318","487,550","565,549","680,694","780,950","831,988",...,"1,142,480","1,374,940","1,419,698","1,694,649","1,745,460","1,879,373","2,013,980","2,133,822","2,382,345","2,489,720"
Subsidies,"77,443","40,006","43,899","91,529","120,765","107,432","150,214","275,291","138,082","192,707",...,"346,420","355,045","391,963","185,971","174,227","166,401","216,883","201,803","196,231","242,087"
Interest payments,"87,142","87,667","65,351","62,485","65,200","79,083","79,806","88,430","93,782","88,383",...,"100,516","113,035","133,441","156,010","182,761","216,568","257,952","275,521","314,088","343,495"
Total (incl. subsidy and interest payment),"352,536","336,119","397,969","448,492","528,283","674,065","795,570","1,044,415","1,012,814","1,113,078",...,"1,589,416","1,843,021","1,945,101","2,036,629","2,102,448","2,262,342","2,488,815","2,611,145","2,892,665","3,075,302"
Transfers (from Central to sub-national levels),"81,054","94,657","120,314","129,723","150,464","226,180","253,263","292,434","308,585","344,728",...,"480,645","513,260","573,703","623,140","710,257","741,992","757,793","812,973","762,530","785,708"

In [10]:
class_df = class_df.transpose()

In [11]:
class_df

Year,1_Personnel,2_Goods and services,3_Capital,4_Grants,5_Others (include financial/social assistance in district level),6_Social Assistance (only at central level),Total (excl. subsidy and interest payment),Subsidies,Interest payments,Total (incl. subsidy and interest payment),Transfers (from Central to sub-national levels)
2001,"85,104","30,227","58,398",-,"14,221",NaN,"187,950","77,443","87,142","352,536","81,054"
2002,"86,154","40,389","61,604",-,"20,299",NaN,"208,446","40,006","87,667","336,119","94,657"
2003,"109,702","47,805","102,772",-,"28,442",NaN,"288,720","43,899","65,351","397,969","120,314"
2004,"126,677","49,593","92,241",-,"25,967",NaN,"294,478","91,529","62,485","448,492","129,723"
2005,"132,353","68,854","69,931",-,"46,276","24,904","342,318","120,765","65,200","528,283","150,464"
2006,"167,556","105,155","119,802",-,"54,328","40,709","487,550","107,432","79,083","674,065","226,180"
2007,"211,616","110,363","152,854","3,916","37,043","49,756","565,549","150,214","79,806","795,570","253,263"
2008,"261,345","122,548","170,638","11,352","57,070","57,741","680,694","275,291","88,430","1,044,415","292,434"
2009,"295,891","155,791","178,323","11,782","65,349","73,814","780,950","138,082","93,782","1,012,814","308,585"
2010,"348,955","178,306","174,451","15,231","46,434","68,611","831,988","192,707","88,383","1,113,078","344,728"
2011,"406,226","230,617","226,214","18,586","31,041","71,104","983,788","295,358","93,262","1,372,408","411,325"
2012,"458,807","261,398","275,147","46,513","24,993","75,621","1,142,480","346,420","100,516","1,589,416","480,645"
2013,"514,048","315,330","368,450","53,144","31,831","92,136","1,374,940","355,045","113,035","1,843,021","513,260"
2014,"556,475","342,018","328,340","54,439","40,502","97,925","1,419,698","391,963","133,441","1,945,101","573,703"
2015,"610,335","426,136","424,088","69,188","67,751","97,151","1,694,649","185,971","156,010","2,036,629","623,140"
2016,"656,987","470,937","392,230","79,484","96,209","49,614","1,745,460","174,227","182,761","2,102,448","710,257"
2017,"669,442","539,377","420,309","73,188","121,760","55,297","1,879,373","166,401","216,568","2,262,342","741,992"
2018,"714,751","615,647","387,364","80,351","131,549","84,318","2,013,980","216,883","257,952","2,488,815","757,793"
2019,"761,043","639,205","396,755","80,629","143,709","112,480","2,133,822","201,803","275,521","2,611,145","812,973"
2020,"753,832","697,304","348,492","94,965","285,223","202,530","2,382,345","196,231","314,088","2,892,665","762,530"
2021,"763,785","845,871","406,986","84,008","215,415","173,654","2,489,720","242,087","343,495","3,075,302","785,708"

In [ ]:
# save as json
class_df.to_json('../data/json/second/second_byFunctions.json')